export default {
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    ADD_PRODUCT: "ADD_PRODUCT",
    SET_PRODUCT: "SET_PRODUCT",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    SET_CUSTOMER: "SET_CUSTOMER",
    ADD_SALE: "ADD_SALE",
    SET_SALE: "SET_SALE",
    SET_PRODUCT_SEARCH: "SET_PRODUCT_SEARCH",
    SET_CUSTOMER_SEARCH: "SET_CUSTOMER_SEARCH",
    SET_SALES: "SET_SALES",
    SET_RECENT_ACTIVITY: "SET_RECENT_ACTIVITY"
}